#!/usr/bin/env bash
# shellcheck shell=bash

# Installs the swarmc/swarmp launcher shims into ~/.local/bin so operator
# guides can use one short command per step. The shims bake in this workspace
# path and self-heal by searching when the baked path goes stale.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib/swarm_core_workspace.sh
source "${SCRIPT_DIR}/lib/swarm_core_workspace.sh"

log() {
  echo "[swarm_core_install_launchers] $*" >&2
}

workspace=""
bin_dir="${SWARM_CORE_LAUNCHER_BIN_DIR:-$HOME/.local/bin}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace)
      shift
      workspace="${1:-}"
      ;;
    --bin-dir)
      shift
      bin_dir="${1:-}"
      ;;
    -h|--help)
      echo "Usage: swarm_core_install_launchers.sh [--workspace <path>] [--bin-dir <path>]"
      exit 0
      ;;
    *)
      echo "[swarm_core_install_launchers] ERROR: Unknown argument: $1" >&2
      exit 1
      ;;
  esac
  shift || true
done

if [[ -z "$workspace" ]]; then
  workspace="$(swarm_core_detect_workspace_root "")" || {
    echo "[swarm_core_install_launchers] ERROR: Could not detect workspace root." >&2
    exit 1
  }
fi

install -d "$bin_dir"

write_shim() {
  local name="$1"
  local rel_path="$2"
  local ensure_hint="$3"
  local shim_path="${bin_dir}/${name}"

  cat >"$shim_path" <<SHIM
#!/usr/bin/env bash
# Generated by swarm_core_install_launchers.sh — rerun it to refresh this shim.
set -euo pipefail
REAL="${workspace}/${rel_path}"
if [[ ! -x "\$REAL" ]]; then
  REAL="\$(find "\${SWARM_SEARCH_ROOT:-\$HOME}" -maxdepth 10 -type f -path "*/${rel_path}" 2>/dev/null | sort | head -n1)"
fi
if [[ -z "\${REAL:-}" || ! -x "\$REAL" ]]; then
  echo "[${name}] Cannot locate ${rel_path} under \${SWARM_SEARCH_ROOT:-\$HOME}." >&2
  echo "[${name}] ${ensure_hint}" >&2
  exit 1
fi
export SWARM_CORE_WORKSPACE_ROOT="${workspace}"
exec "\$REAL" "\$@"
SHIM
  chmod 0755 "$shim_path"
  log "installed ${shim_path}"
}

write_shim "swarmc" "src/swarm_control_core/scripts/swarmc" \
  "Rerun the first-contact bootstrap from ADD_robot_pi.md Step 0."
write_shim "swarmp" "src/swarm_control_pro/scripts/swarmp" \
  "swarm_control_pro is not checked out. Run: ~/.local/bin/swarmc ensure-pro"

path_marker="# swarm_control_core launchers"
if [[ "$bin_dir" == "$HOME/.local/bin" && ":${PATH}:" != *":${bin_dir}:"* ]]; then
  if ! grep -Fq "$path_marker" "$HOME/.bashrc" 2>/dev/null; then
    {
      echo ""
      echo "$path_marker"
      echo "export PATH=\"\$HOME/.local/bin:\$PATH\""
    } >>"$HOME/.bashrc"
    log "added ${bin_dir} to PATH in ~/.bashrc (takes effect in new terminals)"
  fi
fi

log "launchers ready: use ~/.local/bin/swarmc (plain 'swarmc' in new terminals)"
